// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.3
// source: bastion.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UserRole int32

const (
	UserRole_Reporter   UserRole = 0
	UserRole_Developer  UserRole = 1
	UserRole_Maintainer UserRole = 2
	UserRole_Admin      UserRole = 3
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "Reporter",
		1: "Developer",
		2: "Maintainer",
		3: "Admin",
	}
	UserRole_value = map[string]int32{
		"Reporter":   0,
		"Developer":  1,
		"Maintainer": 2,
		"Admin":      3,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_bastion_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_bastion_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{0}
}

type MsgOperation int32

const (
	MsgOperation_Stdin   MsgOperation = 0 //pty stdin
	MsgOperation_Stdout  MsgOperation = 1 //pyt stdout
	MsgOperation_Resize  MsgOperation = 2 //pty screen resize
	MsgOperation_Ping    MsgOperation = 3 //websocket ping
	MsgOperation_Warning MsgOperation = 4 //filter find danger cmd line warning message
)

// Enum value maps for MsgOperation.
var (
	MsgOperation_name = map[int32]string{
		0: "Stdin",
		1: "Stdout",
		2: "Resize",
		3: "Ping",
		4: "Warning",
	}
	MsgOperation_value = map[string]int32{
		"Stdin":   0,
		"Stdout":  1,
		"Resize":  2,
		"Ping":    3,
		"Warning": 4,
	}
)

func (x MsgOperation) Enum() *MsgOperation {
	p := new(MsgOperation)
	*p = x
	return p
}

func (x MsgOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_bastion_proto_enumTypes[1].Descriptor()
}

func (MsgOperation) Type() protoreflect.EnumType {
	return &file_bastion_proto_enumTypes[1]
}

func (x MsgOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgOperation.Descriptor instead.
func (MsgOperation) EnumDescriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{1}
}

type ReqWebXterm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` //the payload of token is up to gRPC server, gRPC caller just uses it as string.
}

func (x *ReqWebXterm) Reset() {
	*x = ReqWebXterm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqWebXterm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqWebXterm) ProtoMessage() {}

func (x *ReqWebXterm) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqWebXterm.ProtoReflect.Descriptor instead.
func (*ReqWebXterm) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{0}
}

func (x *ReqWebXterm) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SshConn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr               string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	User               string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Password           string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	PrivateKey         string `protobuf:"bytes,4,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	PrivateKeyPassword string `protobuf:"bytes,5,opt,name=privateKeyPassword,proto3" json:"privateKeyPassword,omitempty"`
}

func (x *SshConn) Reset() {
	*x = SshConn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SshConn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SshConn) ProtoMessage() {}

func (x *SshConn) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SshConn.ProtoReflect.Descriptor instead.
func (*SshConn) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{1}
}

func (x *SshConn) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *SshConn) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SshConn) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SshConn) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *SshConn) GetPrivateKeyPassword() string {
	if x != nil {
		return x.PrivateKeyPassword
	}
	return ""
}

type ResWebXterm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`           //设置会话的uuid,方便和callback日志做好一一对应
	AssetConn *SshConn `protobuf:"bytes,2,opt,name=assetConn,proto3" json:"assetConn,omitempty"` //资产ssh连接配置信息
	ProxyConn *SshConn `protobuf:"bytes,3,opt,name=proxyConn,proto3" json:"proxyConn,omitempty"` //代理跳板ssh配置,主要用于不同集群网络不通的问题,可以为nil
}

func (x *ResWebXterm) Reset() {
	*x = ResWebXterm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResWebXterm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResWebXterm) ProtoMessage() {}

func (x *ResWebXterm) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResWebXterm.ProtoReflect.Descriptor instead.
func (*ResWebXterm) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{2}
}

func (x *ResWebXterm) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ResWebXterm) GetAssetConn() *SshConn {
	if x != nil {
		return x.AssetConn
	}
	return nil
}

func (x *ResWebXterm) GetProxyConn() *SshConn {
	if x != nil {
		return x.ProxyConn
	}
	return nil
}

//使用ssh-remote-shell 执行script,POST 执行日志到callbackURL
type ReqSshExec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr        string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	User        string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Password    string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	PrivateKey  string `protobuf:"bytes,4,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	Script      string `protobuf:"bytes,5,opt,name=script,proto3" json:"script,omitempty"`
	CallbackURL string `protobuf:"bytes,6,opt,name=callbackURL,proto3" json:"callbackURL,omitempty"`
}

func (x *ReqSshExec) Reset() {
	*x = ReqSshExec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSshExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSshExec) ProtoMessage() {}

func (x *ReqSshExec) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSshExec.ProtoReflect.Descriptor instead.
func (*ReqSshExec) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{3}
}

func (x *ReqSshExec) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ReqSshExec) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ReqSshExec) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReqSshExec) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *ReqSshExec) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *ReqSshExec) GetCallbackURL() string {
	if x != nil {
		return x.CallbackURL
	}
	return ""
}

type ReqAuthLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *ReqAuthLog) Reset() {
	*x = ReqAuthLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAuthLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAuthLog) ProtoMessage() {}

func (x *ReqAuthLog) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAuthLog.ProtoReflect.Descriptor instead.
func (*ReqAuthLog) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{4}
}

func (x *ReqAuthLog) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ReqAssetCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId   string `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	ScriptCmd string `protobuf:"bytes,3,opt,name=script_cmd,json=scriptCmd,proto3" json:"script_cmd,omitempty"`
}

func (x *ReqAssetCmd) Reset() {
	*x = ReqAssetCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAssetCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAssetCmd) ProtoMessage() {}

func (x *ReqAssetCmd) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAssetCmd.ProtoReflect.Descriptor instead.
func (*ReqAssetCmd) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{5}
}

func (x *ReqAssetCmd) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReqAssetCmd) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ReqAssetCmd) GetScriptCmd() string {
	if x != nil {
		return x.ScriptCmd
	}
	return ""
}

//sshd-密码认证
type ReqAuthPassword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User     *ReqSshUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password []byte      `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ReqAuthPassword) Reset() {
	*x = ReqAuthPassword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAuthPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAuthPassword) ProtoMessage() {}

func (x *ReqAuthPassword) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAuthPassword.ProtoReflect.Descriptor instead.
func (*ReqAuthPassword) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{6}
}

func (x *ReqAuthPassword) GetUser() *ReqSshUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ReqAuthPassword) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

//查询资产的ssh帐号
type ReqAssetUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetId string `protobuf:"bytes,1,opt,name=assetId,proto3" json:"assetId,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *ReqAssetUser) Reset() {
	*x = ReqAssetUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAssetUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAssetUser) ProtoMessage() {}

func (x *ReqAssetUser) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAssetUser.ProtoReflect.Descriptor instead.
func (*ReqAssetUser) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{7}
}

func (x *ReqAssetUser) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ReqAssetUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AssetSshAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr       string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	User       string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Password   string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	PrivateKey string `protobuf:"bytes,4,opt,name=privateKey,proto3" json:"privateKey,omitempty"` //可选
}

func (x *AssetSshAccount) Reset() {
	*x = AssetSshAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetSshAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetSshAccount) ProtoMessage() {}

func (x *AssetSshAccount) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetSshAccount.ProtoReflect.Descriptor instead.
func (*AssetSshAccount) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{8}
}

func (x *AssetSshAccount) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *AssetSshAccount) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AssetSshAccount) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AssetSshAccount) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

//sshd-键盘认证
type ReqAuthKeyboard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User          string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SessionId     string `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	ClientVersion string `protobuf:"bytes,3,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	ServerVersion string `protobuf:"bytes,4,opt,name=serverVersion,proto3" json:"serverVersion,omitempty"`
	RemoteAddr    string `protobuf:"bytes,5,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	LocalAddr     string `protobuf:"bytes,6,opt,name=localAddr,proto3" json:"localAddr,omitempty"`
}

func (x *ReqAuthKeyboard) Reset() {
	*x = ReqAuthKeyboard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAuthKeyboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAuthKeyboard) ProtoMessage() {}

func (x *ReqAuthKeyboard) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAuthKeyboard.ProtoReflect.Descriptor instead.
func (*ReqAuthKeyboard) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{9}
}

func (x *ReqAuthKeyboard) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ReqAuthKeyboard) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReqAuthKeyboard) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ReqAuthKeyboard) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *ReqAuthKeyboard) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *ReqAuthKeyboard) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

type ReqSshUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account       string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	SessionId     []byte `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	ClientVersion []byte `protobuf:"bytes,3,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	ServerVersion []byte `protobuf:"bytes,4,opt,name=serverVersion,proto3" json:"serverVersion,omitempty"`
	RemoteAddr    string `protobuf:"bytes,5,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	LocalAddr     string `protobuf:"bytes,6,opt,name=localAddr,proto3" json:"localAddr,omitempty"`
}

func (x *ReqSshUser) Reset() {
	*x = ReqSshUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSshUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSshUser) ProtoMessage() {}

func (x *ReqSshUser) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSshUser.ProtoReflect.Descriptor instead.
func (*ReqSshUser) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{10}
}

func (x *ReqSshUser) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ReqSshUser) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ReqSshUser) GetClientVersion() []byte {
	if x != nil {
		return x.ClientVersion
	}
	return nil
}

func (x *ReqSshUser) GetServerVersion() []byte {
	if x != nil {
		return x.ServerVersion
	}
	return nil
}

func (x *ReqSshUser) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *ReqSshUser) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

//todo:: rename bastion to cmdb
//sshd-公钥认证
type ReqAuthPublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User      *ReqSshUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	PublicKey []byte      `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *ReqAuthPublicKey) Reset() {
	*x = ReqAuthPublicKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAuthPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAuthPublicKey) ProtoMessage() {}

func (x *ReqAuthPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAuthPublicKey.ProtoReflect.Descriptor instead.
func (*ReqAuthPublicKey) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{11}
}

func (x *ReqAuthPublicKey) GetUser() *ReqSshUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ReqAuthPublicKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type UserKb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User        string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Instruction string   `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Questions   []string `protobuf:"bytes,3,rep,name=questions,proto3" json:"questions,omitempty"`
	Answers     []string `protobuf:"bytes,4,rep,name=answers,proto3" json:"answers,omitempty"`
	Echos       []bool   `protobuf:"varint,5,rep,packed,name=echos,proto3" json:"echos,omitempty"`
	ResUser     *User    `protobuf:"bytes,6,opt,name=resUser,proto3" json:"resUser,omitempty"`
}

func (x *UserKb) Reset() {
	*x = UserKb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserKb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKb) ProtoMessage() {}

func (x *UserKb) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKb.ProtoReflect.Descriptor instead.
func (*UserKb) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{12}
}

func (x *UserKb) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UserKb) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *UserKb) GetQuestions() []string {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *UserKb) GetAnswers() []string {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *UserKb) GetEchos() []bool {
	if x != nil {
		return x.Echos
	}
	return nil
}

func (x *UserKb) GetResUser() *User {
	if x != nil {
		return x.ResUser
	}
	return nil
}

//sshd-auth 认证之后用户信息
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Account string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Email   string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone   string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Role    UserRole `protobuf:"varint,6,opt,name=role,proto3,enum=bytegang.UserRole" json:"role,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{13}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_Reporter
}

//sshd-auth 认证之后用户信息
type Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *Group) Reset() {
	*x = Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{14}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

// bastion search and show assets list
type ReqAssetsQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"` //user uuid
	Query  string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`   // full text search keyword
}

func (x *ReqAssetsQuery) Reset() {
	*x = ReqAssetsQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAssetsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAssetsQuery) ProtoMessage() {}

func (x *ReqAssetsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAssetsQuery.ProtoReflect.Descriptor instead.
func (*ReqAssetsQuery) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{15}
}

func (x *ReqAssetsQuery) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReqAssetsQuery) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

//堡垒机-资产信息
type Asset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Alias    string `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Remark   string `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	ShhAddr  string `protobuf:"bytes,5,opt,name=shhAddr,proto3" json:"shhAddr,omitempty"` //资产的ssh-manage-addr
	Ip       string `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *Asset) Reset() {
	*x = Asset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{16}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Asset) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Asset) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Asset) GetShhAddr() string {
	if x != nil {
		return x.ShhAddr
	}
	return ""
}

func (x *Asset) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type AssetList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Asset `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *AssetList) Reset() {
	*x = AssetList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetList) ProtoMessage() {}

func (x *AssetList) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetList.ProtoReflect.Descriptor instead.
func (*AssetList) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{17}
}

func (x *AssetList) GetList() []*Asset {
	if x != nil {
		return x.List
	}
	return nil
}

//堡垒机-资产SSH管理帐号
type ResSshAuthConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User     string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Addr     string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` //密码
	Privatek string `protobuf:"bytes,4,opt,name=privatek,proto3" json:"privatek,omitempty"` //私钥
}

func (x *ResSshAuthConfig) Reset() {
	*x = ResSshAuthConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResSshAuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResSshAuthConfig) ProtoMessage() {}

func (x *ResSshAuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResSshAuthConfig.ProtoReflect.Descriptor instead.
func (*ResSshAuthConfig) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{18}
}

func (x *ResSshAuthConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ResSshAuthConfig) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ResSshAuthConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ResSshAuthConfig) GetPrivatek() string {
	if x != nil {
		return x.Privatek
	}
	return ""
}

//堡垒机-资产SSH管理帐号-查询
type ReqSshAdminQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetId       string `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	AssetIp       string `protobuf:"bytes,2,opt,name=asset_ip,json=assetIp,proto3" json:"asset_ip,omitempty"`
	AssetHostName string `protobuf:"bytes,3,opt,name=asset_host_name,json=assetHostName,proto3" json:"asset_host_name,omitempty"`
}

func (x *ReqSshAdminQuery) Reset() {
	*x = ReqSshAdminQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSshAdminQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSshAdminQuery) ProtoMessage() {}

func (x *ReqSshAdminQuery) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSshAdminQuery.ProtoReflect.Descriptor instead.
func (*ReqSshAdminQuery) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{19}
}

func (x *ReqSshAdminQuery) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ReqSshAdminQuery) GetAssetIp() string {
	if x != nil {
		return x.AssetIp
	}
	return ""
}

func (x *ReqSshAdminQuery) GetAssetHostName() string {
	if x != nil {
		return x.AssetHostName
	}
	return ""
}

//堡垒机-资产SSH管理帐号-查询
type ReqSshUserQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetId       string `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	AssetIp       string `protobuf:"bytes,2,opt,name=asset_ip,json=assetIp,proto3" json:"asset_ip,omitempty"`
	AssetHostName string `protobuf:"bytes,3,opt,name=asset_host_name,json=assetHostName,proto3" json:"asset_host_name,omitempty"`
}

func (x *ReqSshUserQuery) Reset() {
	*x = ReqSshUserQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSshUserQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSshUserQuery) ProtoMessage() {}

func (x *ReqSshUserQuery) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSshUserQuery.ProtoReflect.Descriptor instead.
func (*ReqSshUserQuery) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{20}
}

func (x *ReqSshUserQuery) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ReqSshUserQuery) GetAssetIp() string {
	if x != nil {
		return x.AssetIp
	}
	return ""
}

func (x *ReqSshUserQuery) GetAssetHostName() string {
	if x != nil {
		return x.AssetHostName
	}
	return ""
}

//堡垒机-资产SSH管理帐号-查询
type ReqAssetSsh struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetId string `protobuf:"bytes,1,opt,name=assetId,proto3" json:"assetId,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *ReqAssetSsh) Reset() {
	*x = ReqAssetSsh{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAssetSsh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAssetSsh) ProtoMessage() {}

func (x *ReqAssetSsh) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAssetSsh.ProtoReflect.Descriptor instead.
func (*ReqAssetSsh) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{21}
}

func (x *ReqAssetSsh) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ReqAssetSsh) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

//堡垒机-资产ssh-日志
type ReqSshLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId string `protobuf:"bytes,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
}

func (x *ReqSshLog) Reset() {
	*x = ReqSshLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSshLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSshLog) ProtoMessage() {}

func (x *ReqSshLog) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSshLog.ProtoReflect.Descriptor instead.
func (*ReqSshLog) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{22}
}

func (x *ReqSshLog) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReqSshLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReqSshLog) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type ReqSshCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AssetId string `protobuf:"bytes,2,opt,name=assetId,proto3" json:"assetId,omitempty"`
	Command string `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *ReqSshCmd) Reset() {
	*x = ReqSshCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSshCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSshCmd) ProtoMessage() {}

func (x *ReqSshCmd) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSshCmd.ProtoReflect.Descriptor instead.
func (*ReqSshCmd) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{23}
}

func (x *ReqSshCmd) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReqSshCmd) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ReqSshCmd) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

//rpc 相应状态
type ResStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data   string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ResStatus) Reset() {
	*x = ResStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResStatus) ProtoMessage() {}

func (x *ResStatus) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResStatus.ProtoReflect.Descriptor instead.
func (*ResStatus) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{24}
}

func (x *ResStatus) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ResStatus) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ResStatus) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

//执行远程命令
type ReqExecCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr     string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	User     string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Privatek string `protobuf:"bytes,4,opt,name=privatek,proto3" json:"privatek,omitempty"`
	Script   string `protobuf:"bytes,5,opt,name=script,proto3" json:"script,omitempty"` //shell command or script
}

func (x *ReqExecCmd) Reset() {
	*x = ReqExecCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqExecCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqExecCmd) ProtoMessage() {}

func (x *ReqExecCmd) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqExecCmd.ProtoReflect.Descriptor instead.
func (*ReqExecCmd) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{25}
}

func (x *ReqExecCmd) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ReqExecCmd) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ReqExecCmd) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReqExecCmd) GetPrivatek() string {
	if x != nil {
		return x.Privatek
	}
	return ""
}

func (x *ReqExecCmd) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type RecordFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      string       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Cols      uint32       `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows      uint32       `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Operation MsgOperation `protobuf:"varint,4,opt,name=operation,proto3,enum=bytegang.MsgOperation" json:"operation,omitempty"`
}

func (x *RecordFrame) Reset() {
	*x = RecordFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFrame) ProtoMessage() {}

func (x *RecordFrame) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFrame.ProtoReflect.Descriptor instead.
func (*RecordFrame) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{26}
}

func (x *RecordFrame) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RecordFrame) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *RecordFrame) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *RecordFrame) GetOperation() MsgOperation {
	if x != nil {
		return x.Operation
	}
	return MsgOperation_Stdin
}

type ReqSshdData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid   string         `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`     // ssh session uuid
	Frames []*RecordFrame `protobuf:"bytes,2,rep,name=frames,proto3" json:"frames,omitempty"` //frame of string
}

func (x *ReqSshdData) Reset() {
	*x = ReqSshdData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSshdData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSshdData) ProtoMessage() {}

func (x *ReqSshdData) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSshdData.ProtoReflect.Descriptor instead.
func (*ReqSshdData) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{27}
}

func (x *ReqSshdData) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ReqSshdData) GetFrames() []*RecordFrame {
	if x != nil {
		return x.Frames
	}
	return nil
}

type ResShellExec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Output  string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	StartAt uint64 `protobuf:"varint,3,opt,name=startAt,proto3" json:"startAt,omitempty"`
	DoneAt  uint64 `protobuf:"varint,4,opt,name=doneAt,proto3" json:"doneAt,omitempty"`
	Ok      bool   `protobuf:"varint,5,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *ResShellExec) Reset() {
	*x = ResShellExec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResShellExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResShellExec) ProtoMessage() {}

func (x *ResShellExec) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResShellExec.ProtoReflect.Descriptor instead.
func (*ResShellExec) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{28}
}

func (x *ResShellExec) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ResShellExec) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ResShellExec) GetStartAt() uint64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *ResShellExec) GetDoneAt() uint64 {
	if x != nil {
		return x.DoneAt
	}
	return 0
}

func (x *ResShellExec) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ReqShellExec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target         *SshConn `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Proxy          *SshConn `protobuf:"bytes,2,opt,name=proxy,proto3" json:"proxy,omitempty"`
	ShellScript    string   `protobuf:"bytes,3,opt,name=shellScript,proto3" json:"shellScript,omitempty"`
	Uuid           string   `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TimeoutConnSec uint64   `protobuf:"varint,5,opt,name=timeoutConnSec,proto3" json:"timeoutConnSec,omitempty"`
	TimeoutExecSec uint64   `protobuf:"varint,6,opt,name=timeoutExecSec,proto3" json:"timeoutExecSec,omitempty"`
}

func (x *ReqShellExec) Reset() {
	*x = ReqShellExec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bastion_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqShellExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqShellExec) ProtoMessage() {}

func (x *ReqShellExec) ProtoReflect() protoreflect.Message {
	mi := &file_bastion_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqShellExec.ProtoReflect.Descriptor instead.
func (*ReqShellExec) Descriptor() ([]byte, []int) {
	return file_bastion_proto_rawDescGZIP(), []int{29}
}

func (x *ReqShellExec) GetTarget() *SshConn {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ReqShellExec) GetProxy() *SshConn {
	if x != nil {
		return x.Proxy
	}
	return nil
}

func (x *ReqShellExec) GetShellScript() string {
	if x != nil {
		return x.ShellScript
	}
	return ""
}

func (x *ReqShellExec) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ReqShellExec) GetTimeoutConnSec() uint64 {
	if x != nil {
		return x.TimeoutConnSec
	}
	return 0
}

func (x *ReqShellExec) GetTimeoutExecSec() uint64 {
	if x != nil {
		return x.TimeoutExecSec
	}
	return 0
}

var File_bastion_proto protoreflect.FileDescriptor

var file_bastion_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x61, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x22, 0x23, 0x0a, 0x0b, 0x52, 0x65, 0x71,
	0x57, 0x65, 0x62, 0x58, 0x74, 0x65, 0x72, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x9d,
	0x01, 0x0a, 0x07, 0x73, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x2e,
	0x0a, 0x12, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x83,
	0x01, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x57, 0x65, 0x62, 0x58, 0x74, 0x65, 0x72, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x2f, 0x0a, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67,
	0x2e, 0x73, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x6e, 0x12, 0x2f, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6f, 0x6e, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e,
	0x67, 0x2e, 0x73, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x43, 0x6f, 0x6e, 0x6e, 0x22, 0xaa, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x53, 0x73, 0x68, 0x45,
	0x78, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x52, 0x4c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x52,
	0x4c, 0x22, 0x20, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x41, 0x75, 0x74, 0x68, 0x4c, 0x6f, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x60, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x41, 0x73, 0x73, 0x65, 0x74, 0x43,
	0x6d, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x5f, 0x63, 0x6d, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x43, 0x6d, 0x64, 0x22, 0x57, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x41, 0x75, 0x74, 0x68,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e,
	0x67, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x40,
	0x0a, 0x0c, 0x52, 0x65, 0x71, 0x41, 0x73, 0x73, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x75, 0x0a, 0x0f, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x73, 0x68, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0xcd, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x41,
	0x75, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a,
	0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x22, 0xce, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x53,
	0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x24,
	0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x22, 0x5a, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x41,
	0x75, 0x74, 0x68, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x79, 0x74,
	0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x22, 0xb6, 0x01, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x62, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x63, 0x68, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x08, 0x52, 0x05, 0x65, 0x63,
	0x68, 0x6f, 0x73, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x55, 0x73, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x07, 0x72, 0x65, 0x73, 0x55, 0x73, 0x65, 0x72, 0x22, 0x98, 0x01,
	0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x12, 0x26, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x3f, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0x3e, 0x0a, 0x0e, 0x52, 0x65, 0x71,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x8b, 0x01, 0x0a, 0x05, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x68, 0x68, 0x41, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x68, 0x68, 0x41, 0x64, 0x64, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x30, 0x0a, 0x09, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x72, 0x0a, 0x10, 0x52, 0x65, 0x73,
	0x53, 0x73, 0x68, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6b, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6b, 0x22, 0x70, 0x0a,
	0x10, 0x52, 0x65, 0x71, 0x53, 0x73, 0x68, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x70, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x61, 0x73, 0x73, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x6f, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x53, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x70, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x61, 0x73, 0x73, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x3f, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x73, 0x68, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x53, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x53, 0x73, 0x68, 0x4c, 0x6f, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x53, 0x73, 0x68,
	0x43, 0x6d, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22,
	0x49, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x84, 0x01, 0x0a, 0x0a, 0x52,
	0x65, 0x71, 0x45, 0x78, 0x65, 0x63, 0x43, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x22, 0x7f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x34, 0x0a, 0x09,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x50, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x53, 0x73, 0x68, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67,
	0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x06, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x73, 0x22, 0x7c, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x53, 0x68, 0x65, 0x6c, 0x6c,
	0x45, 0x78, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f,
	0x6e, 0x65, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x64, 0x6f, 0x6e, 0x65,
	0x41, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x22, 0xe8, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x45,
	0x78, 0x65, 0x63, 0x12, 0x29, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x73,
	0x73, 0x68, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x27,
	0x0a, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x73, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x6e,
	0x52, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x65, 0x6c, 0x6c,
	0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x68,
	0x65, 0x6c, 0x6c, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x26, 0x0a,
	0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x53, 0x65, 0x63, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x43, 0x6f,
	0x6e, 0x6e, 0x53, 0x65, 0x63, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x45, 0x78, 0x65, 0x63, 0x53, 0x65, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x45, 0x78, 0x65, 0x63, 0x53, 0x65, 0x63, 0x2a, 0x42, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x72, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x65, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x10,
	0x03, 0x2a, 0x48, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x74, 0x64, 0x69, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x69,
	0x7a, 0x65, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x10, 0x03, 0x12, 0x0b,
	0x0a, 0x07, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x04, 0x32, 0xa5, 0x05, 0x0a, 0x04,
	0x43, 0x6d, 0x64, 0x62, 0x12, 0x35, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x50, 0x77, 0x12, 0x19,
	0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x41, 0x75, 0x74,
	0x68, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x1a, 0x0e, 0x2e, 0x62, 0x79, 0x74, 0x65,
	0x67, 0x61, 0x6e, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x06, 0x41,
	0x75, 0x74, 0x68, 0x50, 0x6b, 0x12, 0x1a, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67,
	0x2e, 0x52, 0x65, 0x71, 0x41, 0x75, 0x74, 0x68, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x1a, 0x0e, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x4b, 0x62, 0x12, 0x14, 0x2e,
	0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x73, 0x68, 0x55,
	0x73, 0x65, 0x72, 0x1a, 0x10, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x4b, 0x62, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0a, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67,
	0x2e, 0x52, 0x65, 0x71, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a,
	0x13, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x13, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x53, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x2e,
	0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x19, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67,
	0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x73, 0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0c, 0x53, 0x73, 0x68, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x45, 0x78,
	0x65, 0x63, 0x12, 0x14, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x52, 0x65,
	0x71, 0x53, 0x73, 0x68, 0x45, 0x78, 0x65, 0x63, 0x1a, 0x13, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67,
	0x61, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12,
	0x3d, 0x0a, 0x0b, 0x57, 0x65, 0x62, 0x58, 0x74, 0x65, 0x72, 0x6d, 0x53, 0x73, 0x68, 0x12, 0x15,
	0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x57, 0x65, 0x62,
	0x58, 0x74, 0x65, 0x72, 0x6d, 0x1a, 0x15, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67,
	0x2e, 0x52, 0x65, 0x73, 0x57, 0x65, 0x62, 0x58, 0x74, 0x65, 0x72, 0x6d, 0x22, 0x00, 0x12, 0x3d,
	0x0a, 0x0b, 0x57, 0x65, 0x62, 0x58, 0x74, 0x65, 0x72, 0x6d, 0x50, 0x6f, 0x64, 0x12, 0x15, 0x2e,
	0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x57, 0x65, 0x62, 0x58,
	0x74, 0x65, 0x72, 0x6d, 0x1a, 0x15, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e,
	0x52, 0x65, 0x73, 0x57, 0x65, 0x62, 0x58, 0x74, 0x65, 0x72, 0x6d, 0x22, 0x00, 0x12, 0x3e, 0x0a,
	0x0e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x53, 0x73, 0x68, 0x64, 0x4c, 0x6f, 0x67, 0x12,
	0x15, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x73,
	0x68, 0x64, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x13, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e,
	0x67, 0x2e, 0x52, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x38, 0x0a,
	0x0a, 0x50, 0x75, 0x73, 0x68, 0x53, 0x73, 0x68, 0x43, 0x6d, 0x64, 0x12, 0x13, 0x2e, 0x62, 0x79,
	0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x73, 0x68, 0x43, 0x6d, 0x64,
	0x1a, 0x13, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x41,
	0x75, 0x74, 0x68, 0x4c, 0x6f, 0x67, 0x12, 0x14, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e,
	0x67, 0x2e, 0x52, 0x65, 0x71, 0x41, 0x75, 0x74, 0x68, 0x4c, 0x6f, 0x67, 0x1a, 0x13, 0x2e, 0x62,
	0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x00, 0x32, 0x47, 0x0a, 0x06, 0x53, 0x73, 0x68, 0x41, 0x72, 0x6b, 0x12, 0x3d, 0x0a,
	0x09, 0x65, 0x78, 0x65, 0x63, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x62, 0x79, 0x74,
	0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x45, 0x78,
	0x65, 0x63, 0x1a, 0x16, 0x2e, 0x62, 0x79, 0x74, 0x65, 0x67, 0x61, 0x6e, 0x67, 0x2e, 0x52, 0x65,
	0x73, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bastion_proto_rawDescOnce sync.Once
	file_bastion_proto_rawDescData = file_bastion_proto_rawDesc
)

func file_bastion_proto_rawDescGZIP() []byte {
	file_bastion_proto_rawDescOnce.Do(func() {
		file_bastion_proto_rawDescData = protoimpl.X.CompressGZIP(file_bastion_proto_rawDescData)
	})
	return file_bastion_proto_rawDescData
}

var file_bastion_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bastion_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_bastion_proto_goTypes = []interface{}{
	(UserRole)(0),            // 0: bytegang.UserRole
	(MsgOperation)(0),        // 1: bytegang.MsgOperation
	(*ReqWebXterm)(nil),      // 2: bytegang.ReqWebXterm
	(*SshConn)(nil),          // 3: bytegang.sshConn
	(*ResWebXterm)(nil),      // 4: bytegang.ResWebXterm
	(*ReqSshExec)(nil),       // 5: bytegang.ReqSshExec
	(*ReqAuthLog)(nil),       // 6: bytegang.ReqAuthLog
	(*ReqAssetCmd)(nil),      // 7: bytegang.ReqAssetCmd
	(*ReqAuthPassword)(nil),  // 8: bytegang.ReqAuthPassword
	(*ReqAssetUser)(nil),     // 9: bytegang.ReqAssetUser
	(*AssetSshAccount)(nil),  // 10: bytegang.AssetSshAccount
	(*ReqAuthKeyboard)(nil),  // 11: bytegang.ReqAuthKeyboard
	(*ReqSshUser)(nil),       // 12: bytegang.ReqSshUser
	(*ReqAuthPublicKey)(nil), // 13: bytegang.ReqAuthPublicKey
	(*UserKb)(nil),           // 14: bytegang.UserKb
	(*User)(nil),             // 15: bytegang.User
	(*Group)(nil),            // 16: bytegang.Group
	(*ReqAssetsQuery)(nil),   // 17: bytegang.ReqAssetsQuery
	(*Asset)(nil),            // 18: bytegang.Asset
	(*AssetList)(nil),        // 19: bytegang.AssetList
	(*ResSshAuthConfig)(nil), // 20: bytegang.ResSshAuthConfig
	(*ReqSshAdminQuery)(nil), // 21: bytegang.ReqSshAdminQuery
	(*ReqSshUserQuery)(nil),  // 22: bytegang.ReqSshUserQuery
	(*ReqAssetSsh)(nil),      // 23: bytegang.ReqAssetSsh
	(*ReqSshLog)(nil),        // 24: bytegang.ReqSshLog
	(*ReqSshCmd)(nil),        // 25: bytegang.ReqSshCmd
	(*ResStatus)(nil),        // 26: bytegang.ResStatus
	(*ReqExecCmd)(nil),       // 27: bytegang.ReqExecCmd
	(*RecordFrame)(nil),      // 28: bytegang.recordFrame
	(*ReqSshdData)(nil),      // 29: bytegang.ReqSshdData
	(*ResShellExec)(nil),     // 30: bytegang.ResShellExec
	(*ReqShellExec)(nil),     // 31: bytegang.ReqShellExec
}
var file_bastion_proto_depIdxs = []int32{
	3,  // 0: bytegang.ResWebXterm.assetConn:type_name -> bytegang.sshConn
	3,  // 1: bytegang.ResWebXterm.proxyConn:type_name -> bytegang.sshConn
	12, // 2: bytegang.ReqAuthPassword.user:type_name -> bytegang.ReqSshUser
	12, // 3: bytegang.ReqAuthPublicKey.user:type_name -> bytegang.ReqSshUser
	15, // 4: bytegang.UserKb.resUser:type_name -> bytegang.User
	0,  // 5: bytegang.User.role:type_name -> bytegang.UserRole
	18, // 6: bytegang.AssetList.list:type_name -> bytegang.Asset
	1,  // 7: bytegang.recordFrame.operation:type_name -> bytegang.MsgOperation
	28, // 8: bytegang.ReqSshdData.frames:type_name -> bytegang.recordFrame
	3,  // 9: bytegang.ReqShellExec.target:type_name -> bytegang.sshConn
	3,  // 10: bytegang.ReqShellExec.proxy:type_name -> bytegang.sshConn
	8,  // 11: bytegang.Cmdb.AuthPw:input_type -> bytegang.ReqAuthPassword
	13, // 12: bytegang.Cmdb.AuthPk:input_type -> bytegang.ReqAuthPublicKey
	12, // 13: bytegang.Cmdb.AuthKb:input_type -> bytegang.ReqSshUser
	17, // 14: bytegang.Cmdb.FetchAsset:input_type -> bytegang.ReqAssetsQuery
	9,  // 15: bytegang.Cmdb.FetchAssetSshConfig:input_type -> bytegang.ReqAssetUser
	5,  // 16: bytegang.Cmdb.SshShellExec:input_type -> bytegang.ReqSshExec
	2,  // 17: bytegang.Cmdb.WebXtermSsh:input_type -> bytegang.ReqWebXterm
	2,  // 18: bytegang.Cmdb.WebXtermPod:input_type -> bytegang.ReqWebXterm
	29, // 19: bytegang.Cmdb.CollectSshdLog:input_type -> bytegang.ReqSshdData
	25, // 20: bytegang.Cmdb.PushSshCmd:input_type -> bytegang.ReqSshCmd
	6,  // 21: bytegang.Cmdb.PushAuthLog:input_type -> bytegang.ReqAuthLog
	31, // 22: bytegang.SshArk.execShell:input_type -> bytegang.ReqShellExec
	15, // 23: bytegang.Cmdb.AuthPw:output_type -> bytegang.User
	15, // 24: bytegang.Cmdb.AuthPk:output_type -> bytegang.User
	14, // 25: bytegang.Cmdb.AuthKb:output_type -> bytegang.UserKb
	19, // 26: bytegang.Cmdb.FetchAsset:output_type -> bytegang.AssetList
	10, // 27: bytegang.Cmdb.FetchAssetSshConfig:output_type -> bytegang.AssetSshAccount
	26, // 28: bytegang.Cmdb.SshShellExec:output_type -> bytegang.ResStatus
	4,  // 29: bytegang.Cmdb.WebXtermSsh:output_type -> bytegang.ResWebXterm
	4,  // 30: bytegang.Cmdb.WebXtermPod:output_type -> bytegang.ResWebXterm
	26, // 31: bytegang.Cmdb.CollectSshdLog:output_type -> bytegang.ResStatus
	26, // 32: bytegang.Cmdb.PushSshCmd:output_type -> bytegang.ResStatus
	26, // 33: bytegang.Cmdb.PushAuthLog:output_type -> bytegang.ResStatus
	30, // 34: bytegang.SshArk.execShell:output_type -> bytegang.ResShellExec
	23, // [23:35] is the sub-list for method output_type
	11, // [11:23] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_bastion_proto_init() }
func file_bastion_proto_init() {
	if File_bastion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bastion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqWebXterm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SshConn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResWebXterm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSshExec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAuthLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAssetCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAuthPassword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAssetUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetSshAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAuthKeyboard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSshUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAuthPublicKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserKb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAssetsQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResSshAuthConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSshAdminQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSshUserQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAssetSsh); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSshLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSshCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqExecCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSshdData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResShellExec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bastion_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqShellExec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bastion_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_bastion_proto_goTypes,
		DependencyIndexes: file_bastion_proto_depIdxs,
		EnumInfos:         file_bastion_proto_enumTypes,
		MessageInfos:      file_bastion_proto_msgTypes,
	}.Build()
	File_bastion_proto = out.File
	file_bastion_proto_rawDesc = nil
	file_bastion_proto_goTypes = nil
	file_bastion_proto_depIdxs = nil
}
